/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    'root': RouteRecordInfo<'root', '/', Record<never, never>, Record<never, never>>,
    '$404': RouteRecordInfo<'$404', '/:404(.*)', { 404: ParamValue<true> }, { 404: ParamValue<false> }>,
    '$error': RouteRecordInfo<'$error', '/:error(.*)', { error: ParamValue<true> }, { error: ParamValue<false> }>,
    'changelog': RouteRecordInfo<'changelog', '/changelog', Record<never, never>, Record<never, never>>,
    'check-update': RouteRecordInfo<'check-update', '/check-update', Record<never, never>, Record<never, never>>,
    'login': RouteRecordInfo<'login', '/login', Record<never, never>, Record<never, never>>,
    'lupa-password': RouteRecordInfo<'lupa-password', '/lupa-password', Record<never, never>, Record<never, never>>,
    'lupa-password-token': RouteRecordInfo<'lupa-password-token', '/lupa-password/:token', { token: ParamValue<true> }, { token: ParamValue<false> }>,
    'monitoring-cetak-rapor': RouteRecordInfo<'monitoring-cetak-rapor', '/monitoring/cetak-rapor', Record<never, never>, Record<never, never>>,
    'monitoring-nilai-ekskul': RouteRecordInfo<'monitoring-nilai-ekskul', '/monitoring/nilai-ekskul', Record<never, never>, Record<never, never>>,
    'monitoring-nilai-pkl': RouteRecordInfo<'monitoring-nilai-pkl', '/monitoring/nilai-pkl', Record<never, never>, Record<never, never>>,
    'monitoring-nilai-projek': RouteRecordInfo<'monitoring-nilai-projek', '/monitoring/nilai-projek', Record<never, never>, Record<never, never>>,
    'monitoring-nilai-ukk': RouteRecordInfo<'monitoring-nilai-ukk', '/monitoring/nilai-ukk', Record<never, never>, Record<never, never>>,
    'monitoring-penilaian': RouteRecordInfo<'monitoring-penilaian', '/monitoring/penilaian', Record<never, never>, Record<never, never>>,
    'monitoring-unduh-legger': RouteRecordInfo<'monitoring-unduh-legger', '/monitoring/unduh-legger', Record<never, never>, Record<never, never>>,
    'nilai-akademik-asesmen-sumatif': RouteRecordInfo<'nilai-akademik-asesmen-sumatif', '/nilai-akademik/asesmen-sumatif', Record<never, never>, Record<never, never>>,
    'nilai-akademik-capaian-kompetensi': RouteRecordInfo<'nilai-akademik-capaian-kompetensi', '/nilai-akademik/capaian-kompetensi', Record<never, never>, Record<never, never>>,
    'nilai-akademik-ekstrakurikuler': RouteRecordInfo<'nilai-akademik-ekstrakurikuler', '/nilai-akademik/ekstrakurikuler', Record<never, never>, Record<never, never>>,
    'nilai-akademik-nilai-akhir': RouteRecordInfo<'nilai-akademik-nilai-akhir', '/nilai-akademik/nilai-akhir', Record<never, never>, Record<never, never>>,
    'nilai-akademik-nilai-sikap': RouteRecordInfo<'nilai-akademik-nilai-sikap', '/nilai-akademik/nilai-sikap', Record<never, never>, Record<never, never>>,
    'nilai-akademik-nilai-sikap-id': RouteRecordInfo<'nilai-akademik-nilai-sikap-id', '/nilai-akademik/nilai-sikap/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'nilai-akademik-nilai-sikap-input-nilai': RouteRecordInfo<'nilai-akademik-nilai-sikap-input-nilai', '/nilai-akademik/nilai-sikap/input-nilai', Record<never, never>, Record<never, never>>,
    'not-authorized': RouteRecordInfo<'not-authorized', '/not-authorized', Record<never, never>, Record<never, never>>,
    'pengaturan-pengguna': RouteRecordInfo<'pengaturan-pengguna', '/pengaturan/pengguna', Record<never, never>, Record<never, never>>,
    'pengaturan-umum': RouteRecordInfo<'pengaturan-umum', '/pengaturan/umum', Record<never, never>, Record<never, never>>,
    'pkl-ketidakhadiran': RouteRecordInfo<'pkl-ketidakhadiran', '/pkl/ketidakhadiran', Record<never, never>, Record<never, never>>,
    'pkl-nilai': RouteRecordInfo<'pkl-nilai', '/pkl/nilai', Record<never, never>, Record<never, never>>,
    'pkl-penilaian': RouteRecordInfo<'pkl-penilaian', '/pkl/penilaian', Record<never, never>, Record<never, never>>,
    'pkl-perencanaan': RouteRecordInfo<'pkl-perencanaan', '/pkl/perencanaan', Record<never, never>, Record<never, never>>,
    'profile': RouteRecordInfo<'profile', '/profile', Record<never, never>, Record<never, never>>,
    'projek-penilaian': RouteRecordInfo<'projek-penilaian', '/projek/penilaian', Record<never, never>, Record<never, never>>,
    'projek-perencanaan': RouteRecordInfo<'projek-perencanaan', '/projek/perencanaan', Record<never, never>, Record<never, never>>,
    'referensi-bobot-penilaian': RouteRecordInfo<'referensi-bobot-penilaian', '/referensi/bobot-penilaian', Record<never, never>, Record<never, never>>,
    'referensi-capaian-pembelajaran': RouteRecordInfo<'referensi-capaian-pembelajaran', '/referensi/capaian-pembelajaran', Record<never, never>, Record<never, never>>,
    'referensi-dudi': RouteRecordInfo<'referensi-dudi', '/referensi/dudi', Record<never, never>, Record<never, never>>,
    'referensi-ekstrakurikuler': RouteRecordInfo<'referensi-ekstrakurikuler', '/referensi/ekstrakurikuler', Record<never, never>, Record<never, never>>,
    'referensi-gtk-asesor': RouteRecordInfo<'referensi-gtk-asesor', '/referensi/gtk/asesor', Record<never, never>, Record<never, never>>,
    'referensi-gtk-guru': RouteRecordInfo<'referensi-gtk-guru', '/referensi/gtk/guru', Record<never, never>, Record<never, never>>,
    'referensi-gtk-instruktur': RouteRecordInfo<'referensi-gtk-instruktur', '/referensi/gtk/instruktur', Record<never, never>, Record<never, never>>,
    'referensi-gtk-tendik': RouteRecordInfo<'referensi-gtk-tendik', '/referensi/gtk/tendik', Record<never, never>, Record<never, never>>,
    'referensi-kompetensi-dasar': RouteRecordInfo<'referensi-kompetensi-dasar', '/referensi/kompetensi-dasar', Record<never, never>, Record<never, never>>,
    'referensi-mata-pelajaran': RouteRecordInfo<'referensi-mata-pelajaran', '/referensi/mata-pelajaran', Record<never, never>, Record<never, never>>,
    'referensi-peserta-didik-aktif': RouteRecordInfo<'referensi-peserta-didik-aktif', '/referensi/peserta-didik/aktif', Record<never, never>, Record<never, never>>,
    'referensi-peserta-didik-keluar': RouteRecordInfo<'referensi-peserta-didik-keluar', '/referensi/peserta-didik/keluar', Record<never, never>, Record<never, never>>,
    'referensi-peserta-didik-password': RouteRecordInfo<'referensi-peserta-didik-password', '/referensi/peserta-didik/password', Record<never, never>, Record<never, never>>,
    'referensi-rombongan-belajar-matpel-pilihan': RouteRecordInfo<'referensi-rombongan-belajar-matpel-pilihan', '/referensi/rombongan-belajar/matpel-pilihan', Record<never, never>, Record<never, never>>,
    'referensi-rombongan-belajar-reguler': RouteRecordInfo<'referensi-rombongan-belajar-reguler', '/referensi/rombongan-belajar/reguler', Record<never, never>, Record<never, never>>,
    'referensi-tujuan-pembelajaran': RouteRecordInfo<'referensi-tujuan-pembelajaran', '/referensi/tujuan-pembelajaran', Record<never, never>, Record<never, never>>,
    'referensi-ukk': RouteRecordInfo<'referensi-ukk', '/referensi/ukk', Record<never, never>, Record<never, never>>,
    'register': RouteRecordInfo<'register', '/register', Record<never, never>, Record<never, never>>,
    'sinkronisasi-dapodik': RouteRecordInfo<'sinkronisasi-dapodik', '/sinkronisasi/dapodik', Record<never, never>, Record<never, never>>,
    'sinkronisasi-erapor': RouteRecordInfo<'sinkronisasi-erapor', '/sinkronisasi/erapor', Record<never, never>, Record<never, never>>,
    'sinkronisasi-kirim-nilai-dapodik': RouteRecordInfo<'sinkronisasi-kirim-nilai-dapodik', '/sinkronisasi/kirim-nilai-dapodik', Record<never, never>, Record<never, never>>,
    'ukk-penilaian': RouteRecordInfo<'ukk-penilaian', '/ukk/penilaian', Record<never, never>, Record<never, never>>,
    'ukk-perencanaan': RouteRecordInfo<'ukk-perencanaan', '/ukk/perencanaan', Record<never, never>, Record<never, never>>,
    'unduhan': RouteRecordInfo<'unduhan', '/unduhan', Record<never, never>, Record<never, never>>,
    'walas-catatan-sikap': RouteRecordInfo<'walas-catatan-sikap', '/walas/catatan-sikap', Record<never, never>, Record<never, never>>,
    'walas-cetak-rapor': RouteRecordInfo<'walas-cetak-rapor', '/walas/cetak-rapor', Record<never, never>, Record<never, never>>,
    'walas-kenaikan-kelas': RouteRecordInfo<'walas-kenaikan-kelas', '/walas/kenaikan-kelas', Record<never, never>, Record<never, never>>,
    'walas-ketidakhadiran': RouteRecordInfo<'walas-ketidakhadiran', '/walas/ketidakhadiran', Record<never, never>, Record<never, never>>,
    'walas-nilai-ekstrakurikuler': RouteRecordInfo<'walas-nilai-ekstrakurikuler', '/walas/nilai-ekstrakurikuler', Record<never, never>, Record<never, never>>,
    'walas-pkl': RouteRecordInfo<'walas-pkl', '/walas/pkl', Record<never, never>, Record<never, never>>,
    'walas-unduh-legger': RouteRecordInfo<'walas-unduh-legger', '/walas/unduh-legger', Record<never, never>, Record<never, never>>,
  }
}
